# Generated by Django 5.1.2 on 2024-12-10 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SeatingArrangment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=5)),
                ('row', models.CharField(max_length=5)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('seating_arrangment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='matches.seatingarrangment')),
            ],
        ),
    ]
