# Generated by Django 5.1.2 on 2024-12-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_stadium_created_by_seatingarrangment_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_datetime', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('seating_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.seatingarrangment')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_a', to='matches.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team_b', to='matches.team')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('match_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.seat')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.team')),
            ],
        ),
    ]
