# Generated by Django 5.1.2 on 2024-12-10 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_ticket_match_instance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Reserved for payment'), (2, 'Sold')], default=0),
        ),
        migrations.CreateModel(
            name='TicketFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=10, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Waiting for payment'), (1, 'Payed'), (2, 'Canceled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='matches.ticketfactor'),
        ),
    ]
